SET STATISTICS IO ON;

CREATE TABLE #T1
(
	col1 INT NOT NULL,
	col2 INT NOT NULL,
	col3 DATE NOT NULL,
	PRIMARY KEY(col1),
	UNIQUE(col2)
);

INSERT INTO #T1(col1, col2, col3)
SELECT n, n * 2, CAST(SYSDATETIME() AS DATE)
FROM dbo.GetNums(1, 1000000);

SELECT col1, col2, col3
FROM #T1
WHERE col2 <= 5;


DROP TABLE #T1;


DECLARE @T1 AS TABLE
(
col1 INT NOT NULL,
col2 INT NOT NULL,
col3 DATE NOT NULL,
PRIMARY KEY(col1),
UNIQUE(col2)
);
INSERT INTO @T1(col1, col2, col3)
SELECT n, n * 2, CAST(SYSDATETIME() AS DATE)
FROM dbo.GetNums(1, 1000000);
SELECT col1, col2, col3
FROM @T1
WHERE col2 <= 5;
GO


SET STATISTICS IO OFF;